binary_versions

Only some bug fixing and better error handling based on the release notes.
Release notes: https://github.com/bitnami-labs/sealed-secrets/blob/master/RELEASE-NOTES.md
The controller is upgraded in the PR: https://github.com/lunarway/lunar-way-sealed-secrets/pull/1

Upgrade sealed-secrets to 0.9.7

---

binary_versions

Let's test if commit signing works

Upgrade to latest release-manager release v0.5.2

---

binary_versions

Fixes a bug in hamctl completion target

Upgrade hamctl and artifact

---

binary_versions

Align with new cluster versions

Update kubectl to 1.18.14

---

binary_versions

This change includes a fix to argument validation in hamctl.

Upgrade hamctl and artifact to 0.12.2

---

binary_versions

Fixes a bug in templates of policy list and rollback commands.

Upgrade hamctl and artifact to 0.16.4

---

binary_versions

This change updates some dependencies and also removes the staging environment
from the promote flows.

Upgrade hamctl to 0.18.0

---

binary_versions

This change contains an new output for hamctl status.

Update hamctl to 0.20.0

---

binary_versions

Added async-schema-tooling schema cli

---

binary_versions

Deprecated binary, has been replaced with `aws eks` util instead

removed iam auth app

---

binary_versions

Upgraded sealed secrets to latest release.

Version bump of sealed secrets v0.21.0

---

binary_versions

Changed binary kubectl version to 1.24.10

Version bumped kubectl to follow the k8s clusters

---

binary_versions

Follow the release deployed on k8s

update sealed secrets binary to v0.23.0

---

binary_versions

version bump sealed secrets v0.24.2

---

binary_versions

Failing builds on generate_config

Revert "chore(deps): update dependency lunarway/shuttle to v0.20.0 (#87)"

---

binary_versions

feat: update shuttle v0.21.1

---

binary_versions

Without a shuttle dir it somehow caused a stack overflow

revert shuttle v0.22.0

---

binary_versions

Fixes: double hash in name issue

shuttle v0.22.3

---

binary_versions

To release the auto login feature in hamctl.

Auto login feature in hamctl

---

binary_versions

seems that it pops the login EVERY time 😭 I will fix the issue in release manager but lets revert until it works as intended

revert version

---

binary_versions

auto login feature added to hamctl

auto-login feature

---

golang_versions

Update version lunarctl to include various bug fixes

chore: update lunarctl version

---

golang_versions

Now including the new versioning scheme

chore: update lunarctl version v0.8.0

---

binary_versions

Reverts lunarway/lw-zsh-versions#134

Revert "fix: remove release manager artifacts"

---

binary_versions

Revert previous.

---

binary_versions

kubectl v 1.30.7

---

binary_versions

Update kubectl to v1.31.10
