- binary_versions
Adds support for template delimiters customisation and a bug fix in git-plan command where output was sometimes empty.
> Update shuttle to 0.10.0

- binary_versions
This reverts commit 151425c03d8d4bce6be58cf38ff1dd786067f523.
We are seeing some odd performance of the new version so we are rolling back and investigating.
> Revert "Update shuttle to 0.10.0 (#13)"

- binary_versions
Includes a fix for stdout and stderr handling on shuttle sub commands
> Upgrade shuttle to 0.10.1

- binary_versions
Addition of stdin flags along with other minor changes. Nothing we use.
https://github.com/bitnami-labs/sealed-secrets/blob/master/RELEASE-NOTES.md#v0126
Tested out locally.
> Update kubeseal to 0.12.6

- binary_versions
Adds `validate` flag to the `run` command for controlling argument validation
> Update shuttle to 0.11.0

- binary_versions
Updating release manager to v0.11.0 is a prerequisite for moving the release manager to the platform cluster.
The version also contains a bug fix for git include definitions﻿
> Update release manager version to v0.11.0

- binary_versions
This upgrades the default version to 1.18.2
> Upgrade to kops 1.18.2

- binary_versions
Contains fixes to hamctl describe releases where an error when getting releases was not reported.
> Upgrade hamctl and artifact to 0.11.2

- binary_versions
Contains support for multi environment releases and better detection of missing VPN connection.
https://github.com/lunarway/release-manager/releases/tag/v0.12.0
> Upgrade hamctl and artifact to 0.12.0

- binary_versions
Contains the new `documentation` command along with strict yaml parsing and other bug fixes.
> Upgrade shuttle to 0.13.1

- binary_versions
Currently only the version name is updated to 1.20.1 but the link still points
to v1.18.2.
This change updates the link. This change will only be reflected with users if
they remove the installed kops version in LW_LOCAL_PATH.
> Fix kops version

- binary_versions
Fixes a bug with large STDOUT and STDERR outputs.
> Upgrade to shuttle 0.13.2

- binary_versions
Contains a new feature where shuttle.yaml is located by traversing the path
tree. This enables shuttle usage in subdirectories of a shuttle project.
> Upgrade shuttle to 0.14.0

- binary_versions
The status command now shows all environments instead of only dev and prod. The
release also contains upgrades to dependencies.
> Upgrade hamctl to 0.19.0

- binary_versions
Version bump:
sealed secrets have changed to tar.gz, using latest version with binary only.
iam-authenticator changed with k8s upgrade to v.0.5.3
Shuttle and release manager changes, following version bumps of server releases.
Do **not** merge, before `prod` cluster has been upgraded.
> version bump developer tools

- binary_versions
I've tested this in dev, using my own script, and I am able to release, and rollback.
I'd rather get this out before actually rolling out release-manager itself
> Update to newest release manager version

- binary_versions
> update shuttle to use 0.17.0

- binary_versions
Because the releases newer than `v0.16.0` do not provide the binary directly
> revert kubeseal to v0.16.0

- binary_versions
Rollback due to a potential problem, where devs do not have updated zplug before the kubeseal is installed.
> Rollback, wait with new kubeseal release

- binary_versions
Updated version of sealed secrets.
Will be released to developers a week after the zsh has been updated.
> Update sealed secrets

- binary_versions
Should disable shuttle golang actions by default
> Update shuttle v0.23.0

- binary_versions
Reverts lunarway/lw-zsh-versions#119. doesn't work
> Revert "Upgrade kubectl to v1.28.12"

- binary_versions
#119 didn't work because there only was one colon after the version
> Upgrade kubectl to v1.28.12

- golang_versions
This is required for the new lunarctl release which cannot be installed using the regular binary_versions file, as we don't have access to private releases using that approach
Fixes: AURA-2482
> feat: add golang versions to maintain what we should install using go install

- renovate.json
Currently, the binaries defined in the `golang_binaries` file are not being updated by renovate and they can fall behind.
This change sets up a regex manager that will make sure the binaries are being updated from this point on.
> Update golang_versions with renovate

- golang_versions
- renovate.json
Currently, Renovate does not correctly understand how to update golang_version releases due to an error in the regex that incorrectly uses the name by itself as the dependency.
This change fixes the issue by setting the dependency name to be the full string eg. `go.lunarway.com/lunarctl`.
> Fix renovate regex

- golang_versions
Currently, we get the warning. This change uses the full github url instead of a redirect.
`"warnings":["Failed to look up github-releases package lunarway/release-manager-artifact","Failed to look up github-releases package go.lunarway.com/lunarctl"]`
> Switch to github url instead of go-packages

- renovate.json
Go install requires the github parts, but renovate doesn't consider it a proper github release
> fix: skip github part of golang_versions

- binary_versions
Theyd gone out of sync, causing issues for renovate
> fix: release manager artifacts same versions

- binary_versions
This wasn't working, and it is far outdated
> fix: remove release manager artifacts

- renovate.json
This should mirror how the packages are actually installed, and doesn't require hacks for getting github releases to work
> feat: add golang versions instead of github releases

- binary_versions
I have verified that this URL works as per @mahlunar 's request 🙏 
https://github.com/lunarway/release-manager/releases/download/v0.30.1/artifact-darwin-amd64
> Update release-manager version.

- CODEOWNERS
- shuttle.yaml
This batch change migrates repository ownership from squad-aura to squad-esa.
The following changes have been applied:
- `shuttle.yaml` squad updated to `esa`.
- `CODEOWNERS` updated to reference `@lunarway/squad-esa`.
**Next Steps:**
- Please ensure that the `squad-esa` team has the appropriate permissions on this repository. (Will be done using a script Tinus made)
[_Created by Sourcegraph batch change `jan/aura-to-esa`._](https://lunar.sourcegraph.com/users/jan/batch-changes/aura-to-esa)
> chore: Migrate squad from Aura to Esa
